spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  profiles:
    active: loadInitialData
  mail:
    host: 'sandbox.smtp.mailtrap.io'
    port: 587
    username: '80ba0fc2e656c8'
    password: '6ab7c47c982f6b'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true